spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
logging:
  level:
    com.ll.exam.sb_security_jwt.app: debug
    org.hibernate.type.descriptor.sql: trace
custom:
  jwt:
    secretKey: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey